// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ukJdkEq8Uxr5XPrmoKxtWURDEUabv7c',
    appId: '1:334818588878:web:f7e6a75d7668155349b89f',
    messagingSenderId: '334818588878',
    projectId: 'maufa-printing',
    authDomain: 'maufa-printing.firebaseapp.com',
    storageBucket: 'maufa-printing.firebasestorage.app',
    measurementId: 'G-S4T22HHPE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHFZcm9adDkjQmA3kyR39fRGNmj0bYkh0',
    appId: '1:334818588878:android:91da931ea78bd5d549b89f',
    messagingSenderId: '334818588878',
    projectId: 'maufa-printing',
    storageBucket: 'maufa-printing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mBtO-PGorI9IAItYz8nz2e8IAj5KhUI',
    appId: '1:334818588878:ios:51bd14922396234749b89f',
    messagingSenderId: '334818588878',
    projectId: 'maufa-printing',
    storageBucket: 'maufa-printing.firebasestorage.app',
    iosClientId: '334818588878-ji9v2l3786l6gnrhgl0pglabmjn7oq5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.maufaPrinting',
  );
}
